### ISSUE TITLE
v5 Vim custom commands

### ISSUE THREAD

**Issue by ElijahKaftanov** [codemirror/CodeMirror#6755] opened 2021-07-29 11:52 UTC
First of all, thanks for the marvelous job you do!
I researched that editor commands are loaded for the execution in the : command input
Is there any possibility to define a custom command by myself like ":wq" to close the window?

**Comment by marijnh** [comment] 2021-07-30 10:13
I'm not aware of the vim mode supporting custom commands, but I'm not deeply familiar with it and the [docs](https://codemirror.net/doc/manual.html#vimapi) are known to be incomplete. Still, since this is the bug tracker, I'm going to close this since it's a question, not a bug.

**Closed by marijnh** 2021-07-30 10:13 UTC
Labels: vim

**Comment by ElijahKaftanov** [comment] 2021-08-08 21:50
@marijnh Can you please tell me, where can I ask this question?

As I found out, vim gets commands from the global command registry of the editor. So can I somehow set custom command to the editor?

**Comment by marijnh** [comment] 2021-08-09 07:00
You can assign to `CodeMirror.commands.[name]` to define new commands in the editor. Asking questions is best done on the [forum](https://discuss.codemirror.net/).

**Comment by benhormann** [comment] 2021-08-09 17:10
> As I found out, vim gets commands from the global command registry of the editor.

Nope, use `CodeMirror.Vim.defineEx`. As Marijn said, RTM: [Extending VIM](https://codemirror.net/doc/manual.html#vimapi_extending).
