### ISSUE TITLE
Code cell is minimally three rows high

### ISSUE THREAD

**Issue by ghuname** [codemirror/CodeMirror#5840] opened 2019-03-29 21:48 UTC
Hi,

I thought I have an issue with jupyterlab so I reported the problem here https://github.com/jupyterlab/jupyterlab/issues/5768#issue-391370312
Several users confirmed the issue. On provided link you can find all details.

A it looks like this is not a jupyter problem, I am reporting the problem here.
Basically, the problem is that on Manjaro linux distribution and firefox, code cell i minimally three rows high. The only workaround is to set zoom level to 150%, but than letters are to small.
Do you have any suggestion for the problem?

**Comment by marijnh** [comment] 2019-03-29 21:59
If you can't reduce the problem down to something involving only plain CodeMirror, I'm not going to be able to take a look at it.

**Comment by jasongrout** [comment] 2019-03-29 22:52
The reason we asked them to file an issue here is that they said they could reproduce it with the codemirror demo page.

@ghuname - can you explain the issue here without referencing JupyterLab or the JLab issue (so @marijnh doesn't need to try to figure out how we are using things in jlab), and only using the stock CodeMirror demo at https://codemirror.net/demo/resize.html (perhaps with a screenshot)?

CC @ian-r-rose who was also able to reproduce the issue with just codemirror.

**Comment by ghuname** [comment] 2019-03-30 12:11
When zoom level is 100% hight is about 3 rows:

![image](https://user-images.githubusercontent.com/15207713/55275856-a675ac80-52ec-11e9-8ddc-bb37743f435c.png)

I can enter two rows of text end cell will not vertically enlarge:

![image](https://user-images.githubusercontent.com/15207713/55275870-d0c76a00-52ec-11e9-9244-85c02f95f9b3.png)


If I add third line, cell hight is just a few pixels bigger:

![image](https://user-images.githubusercontent.com/15207713/55275887-f6ed0a00-52ec-11e9-8491-36a139d80ed7.png)

At zoom level 150%, cell is of the proper hight:

![image](https://user-images.githubusercontent.com/15207713/55275904-1edc6d80-52ed-11e9-91b3-5056f2baf3a4.png)

![image](https://user-images.githubusercontent.com/15207713/55275910-2d2a8980-52ed-11e9-9edb-7f571fb37eb0.png)


I hope it helps.

**Comment by jasongrout** [comment] 2019-03-30 14:16
Thanks, that is helpful! Can you also give the precise firefox version and linux distribution and version?

**Comment by ghuname** [comment] 2019-03-31 00:11
Linux: Manjaro xfce,  4.14.109-1-MANJARO #1 SMP PREEMPT Wed Mar 27 18:51:38 UTC 2019 x86_64 GNU/Linux
Firefox: 66.0.1 (64-bit)

**Comment by marijnh** [comment] 2019-03-31 14:00
Odd, I can't reproduce with Firefox 66 and xfce (but using Debian, not Manjaro)

**Comment by ghuname** [comment] 2019-04-01 19:18
Very strange. Do you have an access to the Manjaro and try on it?

**Comment by marijnh** [comment] 2019-04-02 07:33
No, unfortunately not.

**Comment by ghuname** [comment] 2019-06-02 09:04
I can confirm that in Brave browser (https://brave.com/, based on Chromium) everything works OK.
Looks like the issue is related only to the firefox browser and Manjaro Linux distribution.

**Comment by malaire** [comment] 2019-10-19 11:05
I can't reproduce this with currently available Manjaro releases.

I tried
* manjaro-xfce-18.0.4-stable-x86_64.iso (has Firefox 65.0.2)
* manjaro-xfce-18.1.1-191015-linux53.iso (has Firefox 69.0.3)

**Comment by marijnh** [comment] 2019-10-19 11:34
Then I guess I'll close this until further info is available.

**Closed by marijnh** 2019-10-19 11:34 UTC
