### ISSUE TITLE
Arrow Up doesn't scroll 100% height Codemirror

### ISSUE THREAD

**Issue by jmuharsky** [codemirror/CodeMirror#3906] opened 2016-03-24 17:43 UTC
I have a Codemirror element set to 100% height inside a flex element.  When I arrow down or type, the codemirror box scrolls as expected.  When I use the up arrow (or page up, or jump to top of page, etc.), the scroll position remains where it was.

You can repro this by opening the [PKX application](https://perfkit-explorer.appspot.com/explore?dashboard=5714163003293696&widget=1120041745&container=1578929452) and clicking **EDIT SQL** in the toolbar.  The footer will appear with a SQL editor, and the scroll behavior is as described.

Note this repros on Linux and OSX Chrome v49.

**Comment by marijnh** [comment] 2016-03-25 20:14
Can you reproduce it in _minimal_ HTML page with just CodeMirror an no other scripts/frameworks included?

**Comment by jmuharsky** [comment] 2016-06-03 17:35
Repro'ed here:

https://jsfiddle.net/jmuharsky/kpza6wuu/2/

**Comment by marijnh** [comment] 2016-06-03 21:09
This seems to be a duplicate of #1104

**Closed by marijnh** 2016-06-03 21:09 UTC
