### ISSUE TITLE
'```' for inline code in GFM mode

### ISSUE THREAD

**Issue by Menci** [codemirror/CodeMirror#4137] opened 2016-07-28 06:09 UTC
According to the newest Commonmark spec(http://spec.commonmark.org/0.25/#example-112).

``````
``` aa ```
``````

Should be parsed to a inline code, not a code block with info string 'some thing'. The result on GitHub is same as what commonmark said.

In **markdown** mode, CodeMirror did correct, but in **GFM** mode, it did wrong.

See https://github.com/Moeditor/Moeditor/issues/31 for the screenshot.

And the test code:

`````` html
<!doctype html>
<html>
<head>
    <script src="lib/codemirror.js"></script>
    <script src="mode/markdown/markdown.js"></script>
    <script src="addon/mode/overlay.js"></script>
    <script src="mode/gfm/gfm.js"></script>

    <link href="lib/codemirror.css" rel="stylesheet">
</head>
<body>
    <textarea>
``` aa ```
foo
# title
    </textarea>
    <script>
    (function () {
        var cm = CodeMirror.fromTextArea(document.querySelector('textarea'), {
            lineNumbers: true,
            mode: 'gfm'
        });
    })()
    </script>
</body>
</html>
``````

**Comment by cben** [comment] 2016-09-11 13:05
[Babelmark confirms](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60+aa+%60%60%60) that practically *nobody* parses this as code block.
Only cebe/markdown in GFM or MarkdownExtras modes a `<pre>` but without content.  (Apparently it considers `aa` to be info string, which it doesn't bother to output.)

The CommonMark rule is that info string can't contain any backticks.
A single backtick gives more varied results:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60%60+info+%60%0Acontent%0A%60%60%60
but still only showdown, cebe/markdown in GFM or MarkdownExtras modes consider it a code block.  (many others emit a trailing empty `<pre>` since first ```` ``` info ` ```` didn't open a codeblock, so they consider the last line ```` ``` ```` to open one.)

So I propose adopting CommonMark's rule as very simple and reflecting concensus.

**Comment by adrianheine** [comment] 2018-09-07 08:52
Thanks for your report (and the analysis). I cannot reproduce this issue in [the gfm demo](https://codemirror.net/mode/gfm/index.html), so I suppose it has been fixed in the meantime. Feel free to re-open if that is not the case!

**Closed by adrianheine** 2018-09-07 08:52 UTC
