### ISSUE TITLE
Markdown formatting headings when it shouldn't - v5.29.0 - v5.52.0

### ISSUE THREAD

**Issue by jcontonio** [codemirror/CodeMirror#6171] opened 2020-03-10 21:00 UTC
In all versions from 5.29.0 - 5.52.0, the following happens:

Given the following test, the given value of a CodeMirror textarea will style the first line and second line as a 'cm-header-2'.

Value to try
```
blah blah
-
```

Test HTML/JS
```
<!DOCTYPE html>
<html>
<head>
  <title>CodeMirror formatting bug</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/codemirror.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/codemirror.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/addon/mode/overlay.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/mode/xml/xml.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/mode/markdown/markdown.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.29.0/mode/gfm/gfm.min.js"></script>
  <script>
    window.onload = function() {
      var c = document.getElementById('cmirror')
      CodeMirror.fromTextArea(c, {
        mode: {
          name: 'gfm',
        },
      })
    }
  </script>
</head>
<body>
  <textarea id="cmirror"></textarea>
</body>
</html>
```

<img width="1028" alt="Screen Shot 2020-03-10 at 1 43 06 PM" src="https://user-images.githubusercontent.com/2809/76358136-37fbe580-62d6-11ea-9960-30137e9ea5ed.png">

**Comment by marijnh** [comment] 2020-03-10 21:57
Duplicate of #6129, fixed by 592008812ade98

**Closed by marijnh** 2020-03-10 21:57 UTC
