### ISSUE TITLE
Mousewheel press scrolling issue on Chrome

### ISSUE THREAD

**Issue by r-cristian-v** [codemirror/CodeMirror#5878] opened 2019-05-14 08:23 UTC
I have this minimal setup [here](http://jsfiddle.net/3fdbz0va/).
Steps to reproduce the issue(make sure you are scrolled to the top left of the document):
- press on the mouse wheel to change the scrolling mode
- try and scroll up (obviously won't work since there's nowhere to scroll)
- try and scroll down (won't work)
The same is true for left-right scrolling. This won't happen if you first scroll in a direction that can be scrolled.

Observed this behavior on the latest stable build of Chrome.

**Comment by marijnh** [comment] 2019-05-14 08:27
'scrolling mode' is a new thing to me. Which OS implements it and how does it work?

**Comment by r-cristian-v** [comment] 2019-05-14 08:33
@marijnh Didn't know how to better describe it, when you press down on the mousewheel, the cursor changes and you can scroll a page by moving the mouse. 

 It would correspond to value '1' from [here](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button)

**Comment by marijnh** [comment] 2019-05-14 08:40
Ah, I see. Sounds a lot like the middle-button trackpoint scrolling that I use, but with that I can't reproduce the issue. Have you tried debugging this by seeing whether wheel events are still being fired and how CodeMirror is responding to them.

**Comment by r-cristian-v** [comment] 2019-05-14 09:27
With normal scrolling, 'scroll' and 'mousewheel' events are fired when using the mousewheel. When pressing on the mousewheel and moving the mouse to scroll, only 'scroll' events are fired, which should be normal expected behavior I guess. However, if no scroll is detected on the first mouse movement, Chrome seems to prevent further 'scroll' events from firing for some reason. I'm still searching for further info on this.

**Comment by r-cristian-v** [comment] 2019-05-14 11:47
The issue is definitely Chrome related and not CodeMirror related [fiddle](http://jsfiddle.net/who54vd8/).

The same behavior happens, it has to do with how Chrome handles overflow: scroll. It's just a guess at this point, but maybe it has something to do with chrome://flags/#pull-to-refresh

**Comment by marijnh** [comment] 2019-05-14 11:51
I see, thanks for investigating! If you have time (and haven't already), please file an issue on https://bugs.chromium.org/p/chromium/issues/list . I'm going to close this.

**Closed by marijnh** 2019-05-14 11:51 UTC

**Comment by r-cristian-v** [comment] 2019-05-15 08:33
If anyone somehow ends up here, check [this](https://bugs.chromium.org/p/chromium/issues/detail?id=962904), first comment, second point.
