### ISSUE TITLE
Incorrect/no selection of Arabic(or Arabic with Latin) text

### ISSUE THREAD

**Issue by nethip** [codemirror/CodeMirror#4926] opened 2017-08-22 11:21 UTC
Upon selecting Arabic Text, the selections are not getting shown/sometimes wrong selections are getting shown. Please refer to the GIF video below. I think the problem is with the selections not been shown rather than the selections not happening at all. Also what I have observed is that this is happening more with word wrap on.

![screenrecording](https://user-images.githubusercontent.com/1577184/29563002-5a9a3da4-8759-11e7-9cad-ecd3de45336d.gif)

**Comment by marijnh** [comment] 2017-08-29 21:43
Could you test with attached patch?

**Comment by nethip** [comment] 2017-09-01 11:39
Thanks @marijnh for the patch. We have tested your patch and the selections are much better. However, we have seen some selection issues. 

1. Unable to select the last character without using the keyboard. Please refer to the video below.

![point 1 - unable to select the last character without using the keyboard](https://user-images.githubusercontent.com/1577184/29968030-673dc63a-8f37-11e7-8bc7-b22501522421.gif)

2. Unable to select text from right side. 

![point 2 - unable to start the selection from the right side](https://user-images.githubusercontent.com/1577184/29968041-785e449e-8f37-11e7-89ca-22ad2a60f328.gif)

3. Unable to select just text without selecting the opening and closing tags

![point 4 - unable to select just text without selecting the opening and closing tags](https://user-images.githubusercontent.com/1577184/29968127-db44dfa0-8f37-11e7-9729-167f385a92c5.gif)

**Comment by marijnh** [comment] 2017-09-03 12:13
These all seem to boild down to the fact that many screen positions will correspond to two logical text positions, and if you have text like RRRLLL (where R is rtl and L ltr), selecting from before the first R to after the second will span those two R's, but selecting from that position (which, in the string order, also touches the first L) to in between the L's will get you a region that only covers the Ls.

Some editors seem to do something clever in the first case, apparently swapping the anchor and head of the selection during selecting in some circumstances, but it isn't clear to me how that would generally work.

The second and third seems to work that way in native textareas as well, and are really not avoidable -- a selection is a continuous range in the _string index_ space, not the screen space, so yeah, if you cross bidi boundaries you're not necessarily going to see a coherent selected block on the screen. CodeMirror is definitely not going to change how selections work (and I'm now aware of any tool that does this, and as far as I know this is the expected behavior for RTL users).

**Comment by nethip** [comment] 2017-09-07 11:13
Thanks @marijnh for detailed explanation.

Regarding the first bug, we found that the selections are much better now. But sometimes selection of plain RTL text is not getting shown. Here is a video for the same. I am not sure if it is again related to RRRLL case though.

![point 1a - unable to select the complete line using mouse](https://user-images.githubusercontent.com/1577184/30160562-9778a29a-93ea-11e7-8cd8-bf7eb09cdcde.gif)

**Comment by marijnh** [comment] 2017-09-13 08:07
Hi, could you provide me with a small file that helps reproduce this, and let me know which browser you're using? I can't get it to show up in http://codemirror.net/demo/bidi.html , which has similar text (HTML tags around Arabic content) on Chrome or Firefox.

**Comment by nethip** [comment] 2017-09-13 10:15
Sure @marijnh. Please find the file attachment. I am using chrome browser to test the scenario. And also I am using the `indentwrap.html` demo from `master` to test it.

[ArabicSelection.zip](https://github.com/codemirror/CodeMirror/files/1299057/ArabicSelection.zip)

The problem that I had reported above can be seen on `line no: 70`.

**Comment by marijnh** [comment] 2017-09-13 12:21
I can reproduce this with that file (it seems to require a very specific line). Working on a fix now.

**Comment by marijnh** [comment] 2017-09-13 13:09
Attached patch should solve the problem -- the issue was a bug in the way mouse coordinates were mapped to document positions.

**Comment by nethip** [comment] 2017-09-13 15:47
@marijnh That was super fast 👍 Thanks for the patch! I will try out the new fix and update my findings. Thanks!

**Comment by nethip** [comment] 2017-09-14 04:48
@marijnh I validated your patch and here are my findings. 

The problem looked to be fixed. And even the selection not happening with the last character seems to have got fixed. Thanks for the quick fix 👍 

I am seeing the following issues

1) I am seeing a hang with the following workflow.

![hangdemo](https://user-images.githubusercontent.com/1577184/30411879-a3b04170-9931-11e7-8220-46c4c90914f8.gif)

I figured out that `cm` is going into an infinite loop at the following place.

![devtools](https://user-images.githubusercontent.com/1577184/30412211-765681d8-9933-11e7-99a0-8565d6f15c2d.png)

Coming back to the original issue, third one in https://github.com/codemirror/CodeMirror/issues/4926#issuecomment-326559127, reported above, I see that there no way I can selectively select just part of the text, in some scenarios. I checked the behavior with native `textarea` in  chrome and found a similar behavior. However I found that the user can somehow select the desired text, which is not possible with the current version of `cm`. Here is a video capture of selections inside `textarea`. I think if we can have this behavior in `cm`, the selection issues w.r.t RTL text should go away.

![textareabehaviordemo](https://user-images.githubusercontent.com/1577184/30412459-47fb65b8-9935-11e7-9527-7bce7d4689c1.gif)

**Comment by marijnh** [comment] 2017-09-14 13:43
Indeed, I could reproduce the infinite loops, and I've decided to rewrite the relevant code entirely since it was too scary. See pull request #4968.

Your second issue seems to be a bug in the selection drawing -- since if you delete such a selection, the tag is not actually deleted. I have to work on other things today, but will try to take a look tomorrow.

**Comment by nethip** [comment] 2017-09-14 13:45
@marijnh Thanks for looking into it! I will try out the new fix and update you.

**Comment by nethip** [comment] 2017-09-14 14:52
@marijnh I have tested new patch. I am still seeing the hang upon selection of text in line no 68. I am try to select the text after the <p> tag and and upon reaching COMPANY, the hang is still happening.

**Comment by marijnh** [comment] 2017-09-15 11:27
The selection issue should be better with patch 15b2903cc3.

I'm puzzled how you can still be seeing the hang -- I can't reproduce it anymore, and the related code was rewritten entirely. Are you sure you have the latest code and have rebuilt lib/codemirror.js?

**Comment by nethip** [comment] 2017-09-15 12:57
@marijnh I cloned the repo again and built using 'npm run-script build'. I am running into the same issue.
Here is a video recording of what I doing.

![hangdemo2](https://user-images.githubusercontent.com/1577184/30483057-13ae6a12-9a43-11e7-9978-9a9411cf2df8.gif)

I am on 5c087ac4e4fab2b3d9510caa006616535a207ff6

**Comment by marijnh** [comment] 2017-09-15 13:25
> I am on 5c087ac

Yeah, that's the master branch, which does not have these patches yet. You want to get the patches from #4968.

**Comment by nethip** [comment] 2017-09-15 17:19
Thanks for pointing me to the right branch @marijnh . I thought this patch, to do with infinite loop, made it to `master`. 

I did play around a bit with the branch. I took all changes from `master` and merged them to `coordsCharInner` locally to test out. I can see that the hang is gone. 👍 . I can also see that now the selections shown represent the actual selections inside `cm`.  However I see 2 issues.

1. Selections when starting from LR or RL boundaries are getting inverted. I am not sure if this falls into the same category, you had explained about in https://github.com/codemirror/CodeMirror/issues/4926#issuecomment-326801167

![selectioninversion](https://user-images.githubusercontent.com/1577184/30494664-b6330914-9a66-11e7-8772-516ff4cfce69.gif)


2. Selections are not predictable. When selecting the same block of text I am seeing different selections being set.

![unpredictableselection](https://user-images.githubusercontent.com/1577184/30494682-d1b8660c-9a66-11e7-96db-fabb8b804875.gif)

I want to thank you for taking my feedback and incorporating the required changes.

**Comment by marijnh** [comment] 2017-09-18 09:28
I've merged the update of the coordinate-to-character code.

I think the issue with the non-deterministic selections was about whether the original click happened (a few pixels) in the RTL or the LTR text -- i.e. if you clicked the `<p>` tag, the selection anchor would be in there, which is near the start of the logical line, whereas if you clicked on the first Arabic character, you'd get a position at the end of the logical line. That is indeed confusing, so patch febbe7cb tries to 'fix' ranges created by mouse-drag by adjusting the anchor when it is on such a 'bidi jump' to point in the direction of the current selection head. Does that patch help for you?

**Comment by nethip** [comment] 2017-09-18 09:54
@marijnh Sure! I will update the `master` and start testing.

**Comment by nethip** [comment] 2017-09-18 11:27
@marijnh I have updated the `master` branch on my system and I see that all issues are resolved except for one. On line 71, when I am trying to select the entire block inside `<p>`, I am not able to select the text between `<p>` and `COMPANY`. Please see the video below.

![unabletoselect](https://user-images.githubusercontent.com/1577184/30539858-091f37ec-9c92-11e7-867e-fea25120a485.gif)


Also I cross checked the behavior with `textarea` and barring the above issue, everything is working on par. 👍

**Comment by marijnh** [comment] 2017-09-19 13:26
Agreed, that is odd behavior. I've further tweaked the mouse-selection behavior in c7007784 and it now seems to do the obvious thing in this case and the corner-cases we discussed before. Take a look!

**Comment by marijnh** [comment] 2017-09-19 20:24
> Could you tell me what is the process for creating a distributable zip for posting cm updates to npm?

I'm not sure I get this question right, but all I do when I publish to NPM is letting NPM run the `prepare` script in `package.json` (which runs `rollup -c`).

All these changes are on the master branch now, and they'll be released as 5.30.0 tomorrow.

The rewrite of the selection drawing and coordinate-to-position mapping might have effects in non-RTL scenarios -- those go through that same code.

**Closed by marijnh** 2017-09-19 20:24 UTC

**Comment by nethip** [comment] 2017-09-20 05:59
Thanks @marijnh that helps!
