### ISSUE TITLE
CodeMirror too eager at capturing (middle-click) paste events

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4900] opened 2017-08-07 19:06 UTC
0. be on linux (or some system that has middle-click paste)
1. go to http://codemirror.net
1. select some text in the editor
1. click off of the editor (and observe the highlight color changes to indicate it's not focused anymore)
1. middle click paste, repeatedly

Expected: nothing happens, since there's no text field focused to receive the pastebuffer contents

Actual: CodeMirror pastes the pastebuffer contents into itself, even though it's not focused

If this behavior is helpful for some use-cases, could an option be added to disable it?

**Comment by marijnh** [comment] 2017-08-08 08:59
Which browser did this happen in? I'm not seeing it in Firefox or Chrome. The editor definitely doesn't register any global handlers related to this, so I'm not sure how it can be happening when it's lost focus.

**Comment by mtaran-google** [comment] 2017-08-19 01:04
Heh, okay, I got a chance to play around with this some more. Try this:

1. http://codemirror.net
1. triple click on one of the lines (e.g. line 7) to select it all
1. move your mouse *directly to the right*, so that it's outside the border of the CodeMirror, but not above or below it.
1. middle-click

**Comment by marijnh** [comment] 2017-08-19 16:33
I can see this happen now -- even when the editor isn't focused. My best guess is that Chrome is using some kind of heuristic to find the element that the user might have meant to click on... the mouse target isn't related to CodeMirror there, and the focus isn't on it, so from what I understand of the DOM, there really isn't any reason to deliver the pasted content on the editor, yet it does. No paste event is fired, either.

The fact that this only happens up to a certain pixel distance from the editor seems to also point in the direction of a misguided heuristic. But interestingly, I can't reproduce this with a plain textarea, so it might be possible to work around it by changing some DOM structure or CSS value ... I haven't been able to figure out such a workaround yet though.

**Comment by mtaran-google** [comment] 2017-08-20 01:43
FYI, I was reproing this in Firefox too, so I don't think it's chrome
specific.

**Comment by marijnh** [comment] 2017-08-21 08:04
Interesting. I've never had middle-click paste in CodeMirror work in Firefox, and right now (with Firefox 57) middle-click still does nothing -- whether I click inside or outside the editor. Which Firefox version are you using, and do the steps you outlines above cause actual pasting to happen on your system?

**Comment by mtaran-google** [comment] 2017-08-22 18:34
You're right. I was mistaken – I never did get it reproing on FF. But for the Chrome specific behavior, would you mind putting together a simpler repro case than the full codemirror, and filing a bug at https://bugs.chromium.org/p/chromium/issues/list? If you link it here, I can comment on it to get it prioritized a bit.

**Comment by marijnh** [comment] 2017-08-24 11:20
On closer look, this seems to be a behavior that Chrome exhibits for all DOM nodes that aren't input fields or textareas — when a middle mouse paste happens, that's not over a regular input field, it searches for a nearby valid cursor position, which in this case will be in the text inside of the editor, and fires the paste event on _that_.

So it appears that what we're seeing here is what the Chrome developers intended to happen, probably for usability reasons. I also don't see an easy way to disable it, so I would propose to just leave it as it is. Can you live with that?

**Comment by mtaran-google** [comment] 2017-11-17 02:53
I'd rather have the actual discussion with the relevant Chrome developers directly, to determine what it was they did or did not intend. But to do that, I need a small repro case that I can attach to a bug. Since you noted you could get this happening on other input fields, would you mind putting a small one together?

Something super minimalist like 
```html
<html>
<br>
<br>
<input>
```
doesn't appear to repro.

**Comment by marijnh** [comment] 2017-11-17 10:31
Middle-clicking anywhere on this page fires the event handler, though the div only extends to the border.

```
<!doctype html><meta charset="utf-8">

<div style="margin: 5em; border: 1px solid blue">Hello</div>

<script>
  document.querySelector("div").addEventListener("paste", e => console.log("paste event on div"))
</script>
```

**Comment by mtaran-google** [comment] 2017-11-17 19:58
Thanks! Filed https://bugs.chromium.org/p/chromium/issues/detail?id=786490

**Comment by adrianheine** [comment] 2017-11-17 20:01
That issue doesn't seem to be public. At least I cannot see it.

**Comment by mtaran-google** [comment] 2017-11-17 20:04
Ah, yes, it appears visibility-restricted to Google. Sorry about that. But I think the relevant tagging should help prioritize a response.

**Comment by adrianheine** [comment] 2018-09-07 09:38
I'm closing this here and hope that the discussion with the Chrome developers is helpful.

**Closed by adrianheine** 2018-09-07 09:38 UTC

**Comment by ianhi** [comment] 2020-05-17 04:55
Could this issue needs to be re-opened? For both Chrome 81 and Firefox 75 on linux middle clicking outside the editor will paste highlighted text

> 2. triple click on one of the lines (e.g. line 7) to select it all
> 3. move your mouse directly to the right, so that it's outside the border of the CodeMirror, but not above or below it.
> 4. middle-click

I also find that this is true for clicking to the left of the demo:

![codemirror-mid-click](https://user-images.githubusercontent.com/10111092/82136166-ad090100-97d8-11ea-933b-05d58da67161.gif)

**Comment by marijnh** [comment] 2020-05-18 08:05
> Could this issue needs to be re-opened?

It's still not something CodeMirror can help. I can confirm that Firefox is also firing a paste event on the editor in this situation. The event doesn't provide any information that could help distinguish it from a paste inside the editor, so I don't see a way for the library to avoid this. You could open a bug report for Firefox if you want (the issue can be reproduced without CodeMirror by registering a paste event handler on a block element that has visible content, and middle-clicking in the margin next to that element).

**Comment by natewiebe13** [comment] 2020-08-06 17:09
Experiencing something similar where if you middle click outside of the editor, hold it, then release with the cursor on the editor, it will paste the contents.

Would a solution be to listen to the mouse down and mouse up events, determine if the mouse down was on while on the editor and use that to block the event?
