### ISSUE TITLE
Line numbers hidden on IE11 with a custom jQuery scrollbar

### ISSUE THREAD

**Issue by pmrotule** [codemirror/CodeMirror#3105] opened 2015-02-25 21:37 UTC
I have a weird bug on IE11 when I hide the browser scrollbar like this (to add a custom jQuery scrollbar):

```
#container{
    height: 500px;
    width: 100%;
    overflow: hidden;
}

#content{
    width: 100%;
    height: 100%;
    overflow: auto;
    padding-right: 100px;
}
```

When I paste a large block of text (which reveals the scrollbar), the whole textarea jumps one step to the left hiding the line numbers. Nothing happens if I try to call cm.refresh() or cm.setSize(). Demo : http://jsfiddle.net/pmrotule/ezy9so2o/3/

I don't have the bug if I add the same large block of text with cm.setValue() like here : http://jsfiddle.net/pmrotule/ezy9so2o/5/

The only way that I found to go back to normal is to remove the padding-right, wait 2ms (doesn't work without a timeout) then put it back to 100px. It works but it's super ugly (if I call it inside a scroll event, it will still jump one step to the left then go back to normal).

By the way, I also tried the simplescrollbars addon and there was also a bug when I pasted a large block of text (this one not only on IE11, also on Chrome) : after pasting, I was not able to scroll to the very end of the textarea anymore (around 20 lines missing at the end).

I hope my post can help improving Code Mirror. Thank you!

**Comment by marijnh** [comment] 2015-03-02 09:25
You jsfiddle links are 404s. Maybe jsfiddle garbage-collects overbig files? You should, in any case, simply *link* the CodeMirror scripts and stylesheets, rather than including them in the fiddle, to make it easier to see your actual code. Also, make sure you use `<!doctype html>` to put IE into standards mode.

I also can't reproduce the simplescrollbars bug you describe. If I paste the content of codemirror.js into http://codemirror.net/demo/simplescrollbars.html , I can still scroll to the end. (Though the scrollbar thumb was way too tiny, which I've fixed in 78cad27f974c2a84f43.)

**Closed** 2015-09-02 12:00 UTC
