### ISSUE TITLE
[closebrackets] in comment, addon closes parens but not quotes

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#5058] opened 2017-10-30 20:39 UTC
https://codemirror.net/demo/closebrackets.html

Repro:
1. add `//` to a line
2. type `(` after it
3. type `'` after it

Expected:
Either they should both be completed with the closing pair (preferable), or neither of them should be.

Actual:
A `)` is automatically inserted, but a `'` is not

**Comment by BinaryBrain** [comment] 2017-10-30 23:02
I think it's not a bug, because when you type comments in English for instance, you want to close your parentheses but not apostrophes. If you write `// Don't break my code`, you don't want it to become `// Don''t break my code`.

**Comment by mtaran-google** [comment] 2017-10-30 23:11
That's fair, but it should at least A) include some way to customize this special-casing, and B) at least pair up `"`, since in natural language usage that one is pretty univerally paired up with another `"`.

**Comment by marijnh** [comment] 2017-11-01 09:54
Quote-closing in general does not work in contexts that don't tokenize quoted strings, because it is impossible to generally decide whether a quote opens or closes a string. This is intentional—even with a bunch of heuristics (recognizing comment or nested string context, counting quotes, etc) this'd be very error-prone, and I don't want to go there.

**Closed by marijnh** 2017-11-01 09:54 UTC

**Comment by mtaran-google** [comment] 2017-11-02 21:45
I'm not sure I understand why tokenization is relevant here. Is tokenization (or other non-local info) used for closing other types of brackets? It doesn't appear to be, since if you type `)`, go left, and then type `(`, it does the naive thing and just inserts `()`, resulting in the nonsensical `())`.

Looking at other editors/IDEs:
- Sublime appears to use some heuristics in comments, different from the heuristics in tokenized code (e.g. if you have the cursor before """" in comments and mash ", you will type over the existing quotes and continue, whereas in normal code you'd type new quotes and would always have four quotes in front of your cursor)
- Atom and VSCode appear to still do tokenization, and the behavior seems to be the same inside a comment and outside
- IntelliJ just doesn't complete () or "" in comments at all.

These behaviors above appear sensible/internally-coherent, whereas CodeMirror's does not. Could you expound on why Sublime's and Atom's/VSCode's approaches wouldn't be workable for CodeMirror?

**Comment by marijnh** [comment] 2017-11-02 22:34
> I'm not sure I understand why tokenization is relevant here.

Because, if the opening and closing character are the same, it is unclear whether a given insertion should open or close. In a context where the string is tokenized, the token information can be used to figure out whether we are in a position that would open or close a string. In the absence of that, we can't. 

I don't see how what CodeMirror does is any less coherent than the others.

**Comment by mtaran-google** [comment] 2017-11-03 21:06
It's less coherent because the end user's mental model is unlikely to distinguish between "closing bracket-like-things where the start and end are the same character" vs "closing bracket-like-things where the start and end are different characters", so in a  given context it's more natural to either have them both enabled or both disabled. Or at the very least, it would be great if you could provide an option so we can give this functionality to our end users.

Consider:
- Atom: the [top-level option](https://discuss.atom.io/t/how-to-stop-atom-from-auto-closing-and-swallowing-braces-and-quotes/2566/20) toggles auto-closing of both "" and {} style brackets
- VSCode: The 'editor.autoClosingBrackets' setting toggles whether both styles of brackets are auto-closed.
- Sublime: the 'auto_match_enabled' option toggles whether both styles of brackets are auto-closed.
- IntelliJ alone gives two separate top-level prefs, one for quotes and one for brackets (but still, neither of them apply in a comment context)

**Comment by marijnh** [comment] 2017-11-04 12:14
What do those preferences have to do with it? CodeMirror allows enabling/disabling of matching with the `autoCloseBrackets` option + finer grained control.

As I said before, I don't know of a solid way to implement what you're asking for.

**Comment by mtaran-google** [comment] 2017-11-07 03:09
The point I was trying to make with the options that other editors give was that other editors generally have only one option that toggles auto-closing of both "" and {} style brackets. Since these options are intended for user configuration, this is evidence for the fact that *the authors of those editors thought that their users most commonly want the same behavior for "" and {} style brackets*. I'm generally in agreement with those authors.

There are several ways that you could help:
1. Provide an option that just disables all bracket autoclosing in comment context
2. Change the modes (at least e.g. google modes) to do string tokenization inside comments. Strings inside comments wouldn't be styled any differently from plain comments, but then you'd be able to match quotes inside strings, right? Or would it be hard to make the case of e.g. `/** " */` properly close both the comment and the string at the `*/`?
3. Use Sublime's heuristics (which it also appears to use in all other contexts without tokenized strings, e.g. plain text mode):
  - When a user types a quote:
   ```
    if next char is same kind of quote:
      move right
    elif prev char is \w \d or same kind of quote:
      insert only one quote
    elif next char is \s (or end of line) or in `}])`:
      insert two quotes
    else:
      insert only one quote
   ```
   - When this happens in multi-selection, if the prescribed behaviors are the same in each selection, do that behavior. If the prescribed behaviors are different, just insert one copy of the quote at each selection.
   - When backspacing, if the prev and next chars are both the same quote, delete them both.

Number 2 or 3 would definitely be preferable, of course.

**Comment by marijnh** [comment] 2017-11-07 10:50
That heuristic seems to catch most cases—it seems the code was already doing all of that except for the check for a word char before the cursor. Attached patch adds this, replacing the string token heuristic. This will lead to suboptimal behavior when a string ends in a non-word character and is, for some reason, not closed by the automatically inserted matching quote from the opening quote, but it's much simpler.

Does this work for you?
