### ISSUE TITLE
Double horizontal scroll

### ISSUE THREAD

**Issue by gear-waypro** [codemirror/CodeMirror#5105] opened 2017-11-30 22:17 UTC
Hi, i'm using version 5.32.1 and i get a double horizontal scroll has is shown in picture ![doublescroll](https://user-images.githubusercontent.com/8321749/33457111-2e854164-d600-11e7-87d0-a5e8aefc697b.png)

the editor is in a modal window.

my code:
var codeJS; // global

//in document ready event...
codeJS = CodeMirror.fromTextArea(document.getElementById("txtScript"), {
        mode: "javascript",
        //value: "\n\n\n\n",
        indentWithTabs: true,
        smartIndent: true,
        lineNumbers: true,
        matchBrackets: true,
        theme: 'vs2017',
        //autofocus: true,
        extraKeys: { "Ctrl-Space": "autocomplete" }
    });

finally when a modal is shown...
codeJS.setValue(vM.JavaScript);
setTimeout(function () {
            codeJS.refresh();
            codeJS.focus();
            codeJS.setCursor(codeJS.lineCount(), 0);
        }, 500);

sorry for my english. I do my best
thanks for help

**Comment by marijnh** [comment] 2017-12-01 09:18
This doesn't happen in the demos, so it's probably caused by some CSS you added. Try simplifying your setup until it goes away.

**Comment by adrianheine** [comment] 2018-09-07 09:47
Closing this until there's further information.

**Closed by adrianheine** 2018-09-07 09:47 UTC
