### ISSUE TITLE
Opera - text measurements are off when zoomed in/out

### ISSUE THREAD

**Issue by peterkroon** [codemirror/CodeMirror#1146] opened 2013-01-09 14:02 UTC
- Open Opera browser
- Go to: http://codemirror.net/test/
- Zoom twice in or out
- Refresh page to run the tests.

````
2 failures
core_measureEndOfLine
assertion failed (not at right)
core_moveVstuck
{line:0,ch:29} != {line:0,ch:26}
````

Not sure if this is an Opera bug or not.

Opera stable
w7 32 ultimate

**Comment by sukima** [comment] 2015-03-08 18:48
May be related:

    $ git checkout master
    $ git pull origin master
    $ npm install
    $ npm test

    > codemirror@5.0.1 test /Users/suki/source/CodeMirror
    > node ./test/run.js

    core_measureEndOfLine
    assertion failed (not at right)

    1 failure

    { [Error: Command failed: 2015-03-08 14:44:10.370 phantomjs[54443:5703212] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
    ] killed: false, code: 1, signal: null }
    2015-03-08 14:44:10.370 phantomjs[54443:5703212] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.

    npm ERR! Test failed.  See above for more details.

**Comment by marijnh** [comment] 2015-03-08 19:01
Which Opera version on which platform?

**Comment by sukima** [comment] 2015-03-08 19:28
@marijnh Are you asking me? This was with PhantomJS using the `npm test` command. Opera has nothing to do with it. But since it is the exact same error message it can now be reproduced in two environments (phantom and opera).

**Comment by marijnh** [comment] 2015-03-08 19:37
Ah, sorry, I hadn't seen this was a reply to an old issue. Which version of Phantom, then? My local version (1.9.2-5) passes all tests. But text measuring on Phantom is notably shaky, and its bugs in that area rarely translate to issues with real browsers, so it probably isn't a relevant piece of data.

**Comment by sukima** [comment] 2015-03-08 22:05
PhantomJS 1.9.8 (Max OS X)

**Comment by marijnh** [comment] 2015-03-12 20:14
I upgraded to PhantomJS 1.9.8 (Linux) and the tests still pass for me.

I don't have an OS X development system set up, so I'm not able to further dig into this.

**Comment by martinstarman** [comment] 2015-04-17 12:45
I can reproduce this issue. If I zoom to 75 %, this test failed:
* `scroll_movedown_resize`
* `scroll_moveright_scroll`

If I zom to 90 %, this tests failed:
* `core_lineWidgetChanged`
* `scroll_moveright_scroll`

Opera, version 28.0.1750.51, stable channel, Win7 32b.

**Comment by marijnh** [comment] 2015-11-23 11:37
Okay, Presto is dead and this never was very major, so I'm going to close this.

**Closed by marijnh** 2015-11-23 11:37 UTC
