### ISSUE TITLE
getCursor

### ISSUE THREAD

**Issue by bl0zis** [codemirror/CodeMirror#3181] opened 2015-04-04 23:59 UTC
Hello!

Why codemirror return wrong line number?
![sem titulo](https://cloud.githubusercontent.com/assets/6217617/6995167/cfd94954-db2e-11e4-9242-ca19898aa12e.png)

My configuration:

    lineNumbers: true,
    lineWrapping: true,
    styleActiveLine: true,
    mode: "markdown",
    matchBrackets: true

Event: 

	editor.on('mousedown', function(e){
	     console.log(editor.getCursor(true))
	});

or how I can replace for exemple second "![]()" ?

**Comment by marijnh** [comment] 2015-04-05 19:57
None of this is very helpful for actually figuring out what your problem is. I can assure you that `getCursor` works just fine. What may have confused you is that CodeMirror numbers lines from 0, but by default displays line numbers starting at 1, so there's a mismatch between the line number displayed and the actual line numbers. This is by design, and documented in the manual.

I'm closing this. If you have specific questions and want to take the time to actually explain what you are doing, what you expect to happen, and what actually happens (in text, not with context-less screenshots and code snippets), add another comment.

**Closed by marijnh** 2015-04-05 19:57 UTC

**Comment by bl0zis** [comment] 2015-04-06 17:09
@marijnh Hello, now i'm making an markdown editor based on codemirror and marked.js edited by me.
I identify every image automatically, for example when someone write []() it is replaced with editor.setValue(x) to {>ID OF IMAGE<}[](), but I don't want to see {>x<}. is possible to replace the text but placing {>x<} on span with specific class? or configure codemirror to put this : {><} on span automatically?

**Comment by marijnh** [comment] 2015-04-07 07:40
You might want to use the [`markText`](http://codemirror.net/doc/manual.html#markText) method. Also, don't use `setValue` to update small pieces of content, use [`replaceRange`](http://codemirror.net/doc/manual.html#replaceRange) instead, which will leave the rest of the document alone.

**Comment by bl0zis** [comment] 2015-04-08 14:51
@marijnh Hello, yes, I will use markText, it's perfect  to what I want, and yes replaceRange is better,
but how I can localize {><}![]() on text and get number of line & char ? ex:
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce rhoncus non dui eu ullamcorper. In consectetur metus lorem, {><}![]() nec dapibus mauris tristique maximus.

**Comment by marijnh** [comment] 2015-04-08 14:59
You could try the [searchcursor addon](http://codemirror.net/doc/manual.html#addon_searchcursor). In general, try skimming through the whole manual at least once, so that you don't have to ask here or on stackoverflow about every little thing.

**Comment by bl0zis** [comment] 2015-04-08 21:44
Sure!
Thank you a lot!
