### ISSUE TITLE
Caps lock on iOS

### ISSUE THREAD

**Issue by facundomedica** [codemirror/CodeMirror#4121] opened 2016-07-18 01:29 UTC
When I start writing on my iPhone, **the caps keeps locked.** And the shift button that is on the keyboard does not match what the editor is doing. For example, if the caps are locked the shift button should show a little bar below the arrow, but it doesn't, it shows it like a "temporary capitalization" (Like when you start typing in a form field).

**Comment by marijnh** [comment] 2016-07-18 08:03
Duplicate of #3403

**Closed by marijnh** 2016-07-18 08:03 UTC
