### ISSUE TITLE
[merge] merge spacers don't disappear smoothly when copying content from an original into the editor

### ISSUE THREAD

**Issue by takamori** [codemirror/CodeMirror#4537] opened 2017-02-03 06:44 UTC
The content is copied over, shifting the spacer down, before the spacer gets removed. This can be seen here: https://jsfiddle.net/0a74t941/1/ 

It becomes more visible if the spacer is styled to not be an empty space; this can be easily illustrated by specifying the following grey background styling in the CSS:
```
.CodeMirror-merge-spacer {
  background: #eee;
}
```

The interaction here would feel smoother if there would be no frame that renders the in-between state.

**Comment by mtaran-google** [comment] 2017-02-10 22:30
ping :)

this also falls under our support contract

**Comment by marijnh** [comment] 2017-02-10 22:47
There have been several similar questions in the past, also from Google, related to the delay introduced by the merge addon when it reacts to changes. The situation is that computing diffs is too expensive to do synchronously, so unless someone comes up with an incremental implementation of a diff algorithm, it's hard to update the display synchronously, and you're going to see things update with a slight delay.

**Comment by mtaran-google** [comment] 2017-02-10 23:04
That's a separate issue.

The problem here is that *only the text* gets copied, whereas what's actually desired is that *the text and the spacer* get copied, since the *text+spacer* in one pane will (in aligned mode) have the same height as the *text+spacer* in the other pane, hence producing no flicker.

**Comment by marijnh** [comment] 2017-02-11 22:04
> That's a separate issue.

Not really -- it's a symptom of the same issue. Copying a chunk is handled as a regular document change, which results in the interface updating in the way it does for document changes.

We could special-case this and just delete any spacers below the chunks, but in a three-way merge UI it seems there can be situations where this isn't appropriate (since the nearby spacer in the middle view might be creating space for a chunk in other view, note the one that the merged chunk came from).

Adding more complexity just to address this case seems uncalled for, since the symptoms are the same as with other editing actions. So I'm closing this as being a feature request, not a bug report.

**Closed by marijnh** 2017-02-11 22:04 UTC

**Comment by mtaran-google** [comment] 2017-02-13 07:42
I maintain that not doing this is essentially not following through on the intent of the past contract for the aligned mode.

If you won't fix this issue, can you at least expose an API for customizing what the arrows do on click, so that we can fix this ourselves? I think there might be a separate recent bug on this.

**Comment by marijnh** [comment] 2017-02-13 09:41
Attached patch implements an option to customize the code that's run when a chunk is reverted.
