### ISSUE TITLE
Vertical scrolling in large documents is broken in Edge

### ISSUE THREAD

**Issue by ryantrem** [codemirror/CodeMirror#3757] opened 2016-01-06 05:30 UTC
In large documents (e.g. 100,000+ lines) in Microsoft Edge, the vertical scroll bar only scrolls to around 75,000 lines, then thinks it is at the end, and it is not possible to scroll down any further. You can still scroll down further by moving the caret (e.g. down arrow key, page down, Ctrl+End, etc.), but then if you try to scroll back up it just pops back to line ~75,000. Maybe this is actually in issue with Edge since it only seems to repro there, but I haven't seen this problem with other text editors in Edge.

This can easily be reproduced by simply pasting 100,000+ lines of text into the CodeMirror editor on the CodeMirror home page (within Microsoft Edge) and then grabbing the scroll bar and scrolling all the way down.

**Comment by marijnh** [comment] 2016-01-12 14:56
Can you tell me what `editor.display.sizer.style.minHeight` (where `editor` is your CodeMirror instance) returns in this situation? Does it change when you add or remove a few lines? There is an issue in Firefox where it would just clip CSS sizes beyond a certain treshold. Maybe Edge has a similar problem.

**Comment by ryantrem** [comment] 2016-01-14 04:09
In the case where I paste 130381 lines (the sample file I am using for testing) of text into the editor at http://codemirror.net/index.html, editor.display.sizer.style.minHeight returns "2607**628**px". If I remove a handful of lines, it returns "2607**228**px". If I add a few lines, it returns "2607**708**px". So it seems like this is a different problem from the one you describe above.

**Comment by marijnh** [comment] 2016-01-24 22:13
I've confirmed that Edge won't size elements bigger than about 1533917 pixels. It'll show the CSS values correctly (unlike the similar [bug in firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1205604)), but if you look at the element's `offsetHeight`, it is clipped.

I'd suggest reporting this as a bug in Edge. You can reproduce it with this trivial HTML page:

```html
<!doctype html>

<div style="height: 3000000px">xyz</div>

<script>
  console.log(document.querySelector("div").offsetHeight)
  // you get 1533917
</script>
```

**Comment by adrianheine** [comment] 2018-09-06 15:59
I'm closing this since it is a browser bug and we are not planning on working around it.

**Closed by adrianheine** 2018-09-06 15:59 UTC
