### ISSUE TITLE
Extra New Line When Paste a Line (Safari Only)

### ISSUE THREAD

**Issue by qiukf** [codemirror/CodeMirror#3135] opened 2015-03-15 19:20 UTC
Mac OS X 10.9.5
Safari 7.1.3 (9537.85.12.18)

Tested on multiple Macs, same problem on Safari. 
An extra blank line is added when paste a whole line.

**Comment by marijnh** [comment] 2015-03-15 20:36
Sounds like a duplicate of #2900

**Closed by marijnh** 2015-03-15 20:36 UTC
