### ISSUE TITLE
Syntax highlighting is not working in iPad (Mobile Safari)

### ISSUE THREAD

**Issue by ShawnBaek** [codemirror/CodeMirror#4406] opened 2016-11-26 12:08 UTC
Syntax highlighting is not working in iPad Safari.

Could you have plan to fix this problem?

**Comment by marijnh** [comment] 2016-11-27 19:34
If I go to http://codemirror.net with Mobile Safari, the highlighting in the demo works just fine. Where are you testing, and do you get any JavaScript errors?

**Comment by adrianheine** [comment] 2018-09-07 09:14
Closing this since we cannot reproduce the problem and there was no further feedback.

**Closed by adrianheine** 2018-09-07 09:14 UTC
