### ISSUE TITLE
Incorrect height when inside a flexbox container

### ISSUE THREAD

**Issue by Azmisov** [codemirror/CodeMirror#3679] opened 2015-12-02 18:23 UTC
The `.CodeMirror-scroll` element has the wrong height when the editor is inside a flexbox container. I've tested in Firefox and Chrome (Ubuntu 15.10), but the problem only occurs in Chrome. This may need to be reported as a browser bug instead. Here is a test case:
```
<!DOCTYPE html>
<html>
<head>
	<style>
		html, body{ height:100%; }
		body{
			margin:0;
			display:flex;
			flex-direction:column;
		}
		.CodeMirror{
			margin:10px;
			border:1px solid black;
			flex-grow:1;
		}
	</style>
	<link rel="stylesheet" href="lib/codemirror.css">
	<script src="lib/codemirror.js"></script>
</head>
<body>
	<script> CodeMirror(document.body, {lineNumbers: true}); </script>
</body>
</html>
```

**Comment by marijnh** [comment] 2015-12-03 20:32
This is a Chrome bug. See also #3231. If you want to spend energy on creating a minimal (without CodeMirror) reproducing page and reporting it to the Chrome people, that'd be awesome (the bug is that `height: 100%` doesn't use the parent's height, even if that is `position: relative`, when that parent is in a flex container).

**Comment by marijnh** [comment] 2015-12-03 20:32
Closing since there doesn't seem to be a known workaround that CodeMirror could apply (if you find one, do comment).

**Closed by marijnh** 2015-12-03 20:32 UTC

**Comment by abhishiv** [comment] 2016-01-14 05:16
Just sept a couple of hours trying to fix it. One way is to set parent as position=absolute and height=100%. And the apply display=flex to grandparent.

**Comment by manoharc07** [comment] 2020-04-03 07:56
> Just spent a couple of hours trying to fix it. In case it helps anyone, one way is to set parent as position=absolute and height=100%. And then apply display=flex and position=relative to grandparent.

U just saved me bruh!
