### ISSUE TITLE
[merge] difficulties scrolling

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4101] opened 2016-07-07 21:26 UTC
Repro:
1. Open up demo/merge.html (with https://github.com/codemirror/CodeMirror/pull/4100)
2. Set height of CodeMirror to 1000px in dev tools
3. Open the following in the left and right panes:
[obfuscatedleft.txt](https://github.com/codemirror/CodeMirror/files/353079/obfuscatedleft.txt)
[obfuscatedright.txt](https://github.com/codemirror/CodeMirror/files/353082/obfuscatedright.txt)
4. Scroll the right editor to the bottom by dragging the scroll bar
5. Hovering over the right editor, attempt to scroll up (this needs to be pretty quick and hard/long-distance in the demo -- it repros more easily in our real setup, since we have a mode on + more other JS work going on)

Expected:
Both editors some fraction of the way up.

Actual:
The left editor moves some random amount upward, betweem 0-30% of the way. The right editor appears to move upwards a little bit and then gets pulled back down to the bottom (or sometimes nearly to the bottom).

You can scroll many times (once you find the right speed/force) and the merge view will still be stuck at the bottom.

**Comment by marijnh** [comment] 2016-07-08 09:59
I don't have a device that does momentum scrolling, so I am probably not looking at the same input, but with scrollbar-dragging or low-speed wheel scrolling, I'm not able to reproduce the behavior you describe. Are there any errors being raised or other pieces of information that might help me narrow this down?

**Comment by mtaran-google** [comment] 2016-07-08 18:05
I repro this on Linux with a normal mouse, so I don't think momentum scrolling is involved. It doesn't repro for you with Linux + mouse?

**Comment by marijnh** [comment] 2016-07-08 19:52
Nope, but maybe I am not understanding you correctly. Are you scrolling up by dragging the right editor's scrollbar?

**Comment by mtaran-google** [comment] 2016-07-08 21:19
Ah, I should have specified. No, the actual problem happens when you use the scroll wheel.

**Comment by marijnh** [comment] 2016-07-09 13:39
Right. I'm using Chrome Linux as well, but neither my trackpad scrolling nor firing emulated wheel evens from software triggers the bug. When you say "find the right speed/force", are you talking about wheel rotation speed?

**Comment by marijnh** [comment] 2016-07-11 08:08
(I spent some more time trying to trigger this, and double-checking the relevant code, but didn't manage to reproduce or come up with any theory that might explain the behavior you're seeing.)

**Comment by adrianheine** [comment] 2018-09-07 08:40
I'm closing this for now until we have information that allows to reproduce the issue.

**Closed by adrianheine** 2018-09-07 08:40 UTC

**Comment by bee0060** [comment] 2021-03-25 06:37
I think I have similar problem.
The information I can share is, I got the issue in verson 5.50.0, but in 5.35.0 everything works fine, I didn't try other versions.
Hope this info can help.
