### ISSUE TITLE
ES6 template strings mess up color coding

### ISSUE THREAD

**Issue by globexdesigns** [codemirror/CodeMirror#3536] opened 2015-09-18 00:14 UTC
Not sure if I should file this here or with CodeMirror, but using template strings with JSX results in broken syntax styling in Brackets.

Sample code that fails:

```
export default class Test extends Component {
    render () {
        return (
            <div className={`${CLS}-Pane`}>
                Oops. Everything below this line is now in the wrong colour.
            </div>
        );
    }
}
```

And here is how CodeMirror renders this (inside Brackets):

![bad](https://cloud.githubusercontent.com/assets/226640/9949223/7f3e224a-5d5f-11e5-81d7-870fe067236b.png)

See https://github.com/adobe/brackets/issues/11714 for more info and other examples.

**Comment by leeoniya** [comment] 2015-09-18 01:07
as mentioned in https://github.com/codemirror/CodeMirror/issues/3026, the a `javascriptmixed` mode may help here.

**Comment by marijnh** [comment] 2015-09-21 11:06
Our JavaScript mode doesn't support JSX yet, so having it get confused by JSX syntax is expected. So this is a duplicate of #3122

**Closed by marijnh** 2015-09-21 11:06 UTC

**Comment by globexdesigns** [comment] 2015-09-21 19:03
This issue is not specific to JSX. Regular Javascript code also suffers from issues when processing template strings. See:

![non-jsx](https://cloud.githubusercontent.com/assets/226640/10001875/ca4dd0f4-6058-11e5-9720-35ea519b3b1d.png)

**Comment by marijnh** [comment] 2015-09-21 19:07
Can you reproduce this in http://codemirror.net/mode/javascript/ ? If so, can you paste (not screenshot) the code that triggers it?

**Comment by globexdesigns** [comment] 2015-09-21 20:07
Yes, I can reproduce this if you use a spread operator before the template string. Try this:
```
class MyClass {
  render () {
    const {test, ...other} = this.props;
    const templateString = something(`${test}another_test`);
    let thisLineIsNotColouredRight = true;
  }
}
```

- Removing the `...other` fixes the issue.
- Removing the variable from the template string fixes the issue.
