### ISSUE TITLE
not possible to apply a background to the *gutter* for the currently selected line

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/CodeMirror#4312] opened 2016-10-14 01:28 UTC
We tried in various ways, but things got messed up with e.g. a line widget on the line above, or when you scrolled left/right. The best we've been able to do was highlight the line number, which doesn't really look appealing. Any way to actually do this?

**Comment by marijnh** [comment] 2016-10-14 12:37
Does adding a gutter line class (say 'highlighted') and styling gutter elements under that class with a background (say `.highlighted .CodeMirror-gutter-elt { background: red }`) work?

**Comment by mtaran-google** [comment] 2016-10-14 18:08
I should have been more specific. I meant we want to use this in the same way as `styleActiveLine`, which currently only affects the part of the line that shows text and not the gutter.

**Comment by marijnh** [comment] 2016-10-15 19:00
Sure, but is there anything about my suggestion that is at odds with that?

**Comment by takamori** [comment] 2016-10-17 18:28
By annotating .CodeMirror-gutter-wrapper.CodeMirror-activeline-gutter with background-color, and then setting background-color: inherit on .CodeMirror-activeline-gutter > .CodeMirror-gutter-elt, one can cover areas where there is a gutter element, but not the cases where the gutter element is omitted.

For instance, if some but not all rows have an annotation, or if some but not all rows have a fold indicator, this will only cover the portion that has the line number and the annotation or fold indicator that may or may not exist on the line, but not the empty spaces in the cases where there is none.

The CodeMirror-gutter-wrapper.CodeMirror-activeline-gutter itself does not have a size that corresponds to the size of the gutter.

**Comment by marijnh** [comment] 2016-10-17 19:08
In recent versions (not released yet) the styling of gutter backgrounds with `addLineClass(line, "gutter", "something")` was broken. Attached patch fixes it, though I'm not sure you were using that code. It was (and is again now) possible to simply add a class with a background color as `"gutter"` line class, and color the gutter like that. Scrolling horizontally works for me. When you add a line widget to that line, the color of the gutter will stretch along the widget, since it is part of this line. Is that the problem you mentioned?

**Comment by adrianheine** [comment] 2018-09-07 09:06
I'm closing this for now since there is no new feedback indicating that the issue is still present.

**Closed by adrianheine** 2018-09-07 09:06 UTC
