### ISSUE TITLE
Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by williamdes** [codemirror/CodeMirror#6658] opened 2021-04-15 16:49 UTC
This is only reported on the latest version of phpMyAdmin (5.1.0) that has [`5.59.2`](https://github.com/phpmyadmin/phpmyadmin/blob/333edd4a793e95a04ee97951ee48807350dca728/package.json#L18)

Not browser nor locale specific

```json
"stacktrace": [
        {
            "func": "Widget/this.onScroll",
            "line": "324",
            "column": "20",
            "context": [
                "      cm.on(\"focus\", this.onFocus = function() { clearTimeout(closingOnBlur//...",
                "    }",
                "",
                "    cm.on(\"scroll\", this.onScroll = function() {",
                "      var curScroll = cm.getScrollInfo(), editor = cm.getWrapperElement().g//...",
                "      var newTop = top + startScroll.top - curScroll.top;",
                "      var point = newTop - (parentWindow.pageYOffset || (ownerDocument.docu//...",
                "      if (!below) point += hints.offsetHeight;",
                "      if (point <= editor.top || point >= editor.bottom) return completion.//...",
                "      hints.style.top = newTop + \"px\";",
                "      hints.style.left = (left + startScroll.left - curScroll.left) + \"px\";"
            ],
            "uri": "js/vendor/codemirror/addon/hint/show-hint.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/addon/hint/show-hint.js"
        },
        {
            "func": "signal",
            "line": "568",
            "column": "61",
            "context": [
                "",
                "  function signal(emitter, type /*, values...*/) {",
                "    var handlers = getHandlers(emitter, type);",
                "    if (!handlers.length) { return }",
                "    var args = Array.prototype.slice.call(arguments, 2);",
                "    for (var i = 0; i < handlers.length; ++i) { handlers[i].apply(null, args); }",
                "  }",
                "",
                "  // The DOM events that CodeMirror handles can be overridden by",
                "  // registering a (non-DOM) handler on the editor for the event name,",
                "  // and preventDefault-ing the event in that handler."
            ],
            "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/lib/codemirror.js"
        },
        {
            "func": "registerEventHandlers/<",
            "line": "7999",
            "column": "15",
            "context": [
                "    // area, ensure viewport is updated when scrolling.",
                "    on(d.scroller, \"scroll\", function () {",
                "      if (d.scroller.clientHeight) {",
                "        updateScrollTop(cm, d.scroller.scrollTop);",
                "        setScrollLeft(cm, d.scroller.scrollLeft, true);",
                "        signal(cm, \"scroll\", cm);",
                "      }",
                "    });",
                "",
                "    // Listen to wheel events in order to try and update the viewport on time.",
                "    on(d.scroller, \"mousewheel\", function (e) { return onScrollWheel(cm, e); });"
            ],
            "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.1.0",
            "scriptname": "js/vendor/codemirror/lib/codemirror.js"
        },
        {
            "func": "patchedCallback",
            "line": "127",
            "column": "45",
            "context": [
                "    'Sa',",
                "  ];",
                "  $.datepicker.regional[''].weekHeader = 'Wk';",
                "  $.datepicker.regional[''].showMonthAfterYear = false;",
                "  $.datepicker.regional[''].yearSuffix = '';",
                "  $.extend($.datepicker._defaults, $.datepicker.regional['']);",
                "}",
                "",
                "if ($.timepicker) {",
                "  $.timepicker.regional[''].timeText = 'Time';",
                "  $.timepicker.regional[''].hourText = 'Hour';"
            ],
            "uri": "index.php?route=%2F",
            "scriptname": "index.php"
        }
    ],
```

**Comment by marijnh** [comment] 2021-04-15 16:58
I think this is a duplicate of #6656

**Closed by marijnh** 2021-04-15 16:58 UTC
