### ISSUE TITLE
[markdown mode] list in quote not parsed correctly

### ISSUE THREAD

**Issue by dalphyx** [codemirror/CodeMirror#4134] opened 2016-07-27 07:51 UTC
I have the following code:

```
> Most markdown syntaxes work inside block quotes.
>
> * Lists
> * Etc
> * *cm*
> 1. cm
> 2. cm
> 3. cm
> 
```

In codemirror markdown or gfm mode, the list parsed wrong. Like this:
<img width="516" alt="codemirror" src="https://cloud.githubusercontent.com/assets/1576121/17167833/bf7074a4-5411-11e6-9dbc-514bc69ac62f.png">

**Comment by adrianheine** [comment] 2018-09-07 08:47
Thanks for your report. I cannot reproduce this issue in [the markdown demo](https://codemirror.net/mode/markdown/index.html), so I suppose it has been fixed in the meantime. Feel free to re-open if that is not the case!

**Closed by adrianheine** 2018-09-07 08:47 UTC
