### ISSUE TITLE
support for JSX.

### ISSUE THREAD

**Issue by abdelouahabb** [codemirror/CodeMirror#3352] opened 2015-06-30 04:51 UTC
Hi,
I just started learning ReactJS, and they use JSX which are javascript, and I guess this will be usefull to add `type="text/jsx"` support ?
https://github.com/abdelouahabb/CodeMirror/commit/521c476de9b8a961a3205e7284863de88d012a96

**Comment by marijnh** [comment] 2015-07-02 20:04
Duplicate of #3122

**Closed by marijnh** 2015-07-02 20:04 UTC
