### ISSUE TITLE
Diff highlighting thrown off by windows newline characters

### ISSUE THREAD

**Issue by owenmli** [codemirror/CodeMirror#5089] opened 2017-11-17 19:09 UTC
When displaying a diff (shell mode):

Left side -> Text with Windows newline character (^M in Vim on unix)

Right side -> Diff result with changes

Upon commit (in gerrit)  of this Windows file from Unix, the newline characters are translated and  Codemirror highlights the wrong lines on the left (offset by however many newline characters you have).

Attached is a file with Windows newline characters. A codemirror diff of this file with some changes will highlight the wrong lines.

[jcat.txt](https://github.com/codemirror/CodeMirror/files/1483498/jcat.txt)

**Comment by adrianheine** [comment] 2017-11-17 19:31
I don't think the diffing is done by CodeMirror or any CodeMirror addon. It's probably somewhere in https://github.com/gerrit-review/gerrit/blob/master/gerrit-gwtui/src/main/java/com/google/gerrit/client/diff/.

**Comment by owenmli** [comment] 2017-11-17 21:07
Oh, sorry! I should mention this is with Gerrit 2.14.

We are using CodeMirror 5.30.0

**Comment by marijnh** [comment] 2017-11-20 11:09
I'm not familiar with Gerrit's setup of the merge addon, and I couldn't get this to appear in the merge demo after trying some obvious things. Could you set up a self-contained demo that shows this happening?

**Comment by adrianheine** [comment] 2017-11-20 11:12
As I wrote, I don't think this is the merge addon at work. Take a look [at this completely random diff](https://gerrit.wikimedia.org/r/#/c/293099/2/includes/site/DBSiteStore.php) rendered by Gerrit 2.13.90.

**Comment by marijnh** [comment] 2017-11-20 11:20
Oh, indeed, CodeMirror's merge addon doesn't appear to be loaded on that page, so it's unlikely to be the cause of the problem. I guess Gerrit has its own diffing tool, and the bug is in there. Closing this until further information pointing at our code is found.

**Closed by marijnh** 2017-11-20 11:20 UTC
