### ISSUE TITLE
Can't backspace or edit existing textarea text on Android

### ISSUE THREAD

**Issue by vanboom** [codemirror/CodeMirror#3086] opened 2015-02-17 00:47 UTC
Hi, 
I am running the latest Android with the stock Google keyboard, and finding that the CodeMirror text area will only accept new characters.  It does not allow backspace to delete characters that are already in the text area. 

To test this, please browse your Android tablet to the CodeMirror home page and try to backspace over the existing text in the box. 

I'll try to dig in the code to help find this issue, but wanted to capture it in the issue list. 

Thanks!

**Comment by marijnh** [comment] 2015-02-17 11:36
This is a duplicate of #2234. Check out the [mobile](https://github.com/codemirror/CodeMirror/tree/mobile) branch for a potential solution.

**Closed by marijnh** 2015-02-17 11:36 UTC
