### ISSUE TITLE
Deleting text throws many exceptions in Android Chrome

### ISSUE THREAD

**Issue by TWiStErRob** [codemirror/CodeMirror#4307] opened 2016-10-12 11:25 UTC
Google Chrome 53 (latest) on Galaxy S5 running Android 5.0.1; reproducible with both Google Keyboard and Samsung Keyboard.

**Repro**:
1. open http://codemirror.net
2. long-tap inside the demo to select a word (this works around #4306)
3. Try to delete contents of the textarea by pressing backspace on the soft keyboard  

**Actual**: deleting stops after a while, and content cannot really be deleted
**Expected**: deletion continues until no content remains before the cursor

**Note**: keeping it pressed or tapping it repeatedly both fail badly. These errors essentially make CodeMirror unusable on Android. Not only the demo, but other sites that use it are affected. And some of these exceptions are thrown when entering text too.

**Diagnostic steps**:
1. Start Google Chrome on Android device
2. Visit http://codemirror.net on the device
3. Plug in the device to a computer
4. Start Google Chrome on computer
5. Visit chrome://inspect on the computer
6. Select codemirror.net tab to inspect  
   _See https://developers.google.com/web/tools/chrome-devtools/remote-debugging/ for more details if it doesn't work._
7. Do the repro above to see what's going on

The following errors show repeatedly:

> Uncaught TypeError: Cannot set property 'data' of undefined
> (anonymous function) @ codemirror.js:8173

---

> Uncaught TypeError: Cannot read property 'nodeType' of null
> walk @ codemirror.js:8480
> domTextBetween @ codemirror.js:8510
> pollContent @ codemirror.js:8388
> (anonymous function) @ codemirror.js:8194

---

> Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> updateLineGutter @ codemirror.js:2170
> buildLineElement @ codemirror.js:2223
> patchDisplay @ codemirror.js:4147
> updateDisplayIfNeeded @ codemirror.js:4056
> endOperation_W1 @ codemirror.js:3642
> endOperations @ codemirror.js:3619
> (anonymous function) @ codemirror.js:3608
> finishOperation @ codemirror.js:2050
> endOperation @ codemirror.js:3605
> (anonymous function) @ codemirror.js:3750

**Comment by justbittin** [comment] 2016-10-24 14:20
This is confirmed.  Our mobile site has broken on android.

Codemirror becomes unstable.

**Comment by justbittin** [comment] 2016-10-25 15:42
Has anyone found a work around for this?  This is a critical bug for android at the moment.

**Comment by TWiStErRob** [comment] 2016-10-25 16:06
I suspected they officially don't support mobile based on the no-response so far and found [this](http://codemirror.net/#browsersupport):

> Support for modern mobile browsers is experimental. Recent versions of the iOS browser and Chrome on Android should work pretty well.

**Comment by marijnh** [comment] 2016-10-25 19:16
Debugging mobile composition behavior is annoying and time-consuming. I did at one point have things working with google keyboard, but I guess it changed again. There are plans to improve composition handling, but it might be a while until someone finds the time to work on that.

**Comment by TWiStErRob** [comment] 2016-10-25 19:55
The thing I don't understand is how HackerRank made it work. I'm doing https://www.hackerrank.com/domains/tutorials/30-days-of-code for fun, and every morning when I wake up I start by solving the problem presented in bed on my phone. I'm at Day 5 and experienced no issues so far. Editing works perfectly fine, apart from a very little jump on focus, but no functionality is broken like on your demo and other uses of CM. On desktop they surely use CM, just checked again, and there's no mobile view/styles as far as I can tell, so it should be the same DOM in my phone.

**Comment by justbittin** [comment] 2016-10-25 20:22
The problem isn't Google Keyboard.  Any keyboard on chrome 53 fails.  This is a contenteditable problem - and codemirror throws a bunch of errors (as described above) then fails to work anymore.

I think it is fair to say that desktops are slowly becoming second to mobiles.

**Comment by 40thieves** [comment] 2016-10-26 16:16
We are also experiencing the `Uncaught TypeError: Cannot read property 'nodeType' of null` issue. Our error reporting leads me to believe that it has existed since at least 5.11.

Our error reporting does not have either of the other issues so I believe they might be regressions in 5.20 (we have been running 5.19 for about a week now).

I've done a little bit of digging and I believe the `nodeType` error might be a race condition. When deleting the last letter on a line, content is polled [here](https://github.com/codemirror/CodeMirror/blob/1523a8b79afab2618e7bedaaf34adf5f232fd15b/src/input/ContentEditableInput.js#L244). When determining the `fromNode` [here](https://github.com/codemirror/CodeMirror/blob/1523a8b79afab2618e7bedaaf34adf5f232fd15b/src/input/ContentEditableInput.js#L255), it attempts to find the `nextSibling` of the previous line. However, by this time the DOM has been updated and this node does not exist. Therefore when `node.nodeType` is checked in `domTextBetween` [here](https://github.com/codemirror/CodeMirror/blob/1523a8b79afab2618e7bedaaf34adf5f232fd15b/src/input/ContentEditableInput.js#L359) it throws. It is perhaps noteworthy that `display.view` *does* contain the deleted node, although it is detached from the DOM.

I'm afraid I'm not familiar enough with the code to figure out where the DOM update might be happening but hopefully this will help someone who is. (I should say that the module splitting done in 5.20 helped tremendously when figuring this much out, so thanks!)

**Comment by marijnh** [comment] 2016-11-15 15:47
Could you see if patches 5012e87723716, da8a35d05e72, and 441641e6cb75e help?

**Comment by marijnh** [comment] 2016-11-15 16:10
Actually, though things are somewhat better now, backspacing across line boundaries still sometimes causes weird problems.

**Comment by marijnh** [comment] 2016-11-15 16:35
Attached patch improves things a little more, but there's still various problems. The fact that Chrome Android doesn't fire a useful key event for backspace anymore is really quite problematic.

**Comment by 40thieves** [comment] 2016-11-15 16:36
Thanks @marijnh. I don't think I have time to have a look today, but hopefully tomorrow

**Comment by 40thieves** [comment] 2016-11-16 16:41
Those patches do seem to prevent the error and make it quite a lot smoother to use.

I am getting an CM invalid character inserted when I delete a line though:

![GIF](https://cloud.githubusercontent.com/assets/424411/20355924/f6b63cf8-ac1a-11e6-846d-67c8c581039b.gif)

I tested on my Nexus 5 with both the Google Keyboard (UK) and Swiftkey. I'm afraid I don't have much more data until we push this out to production to track in error reporting (which we likely won't do until a release).

Hope that helps. Thanks!

**Comment by marijnh** [comment] 2016-11-16 16:46
Yeah, I've seen that happen too. And press-and-holding backspace occasionally does really weird things. And writing multiple spaces in a row will put the cursor in the wrong place. I'll see if I can allocate more time for this before the next release.

**Comment by marijnh** [comment] 2016-11-21 09:49
The zero-width space issue should be solved by patch 692393d. The others will have to wait.

**Comment by 40thieves** [comment] 2016-11-28 12:02
Testing an upgrade 5.21 today and confirmed that the error is fixed, and it feels a little smoother to use. However I'm seeing a couple of bugs that I can replicate on the examples.

Empty newlines are removed when new words are typed:

[GIF](https://cloud.githubusercontent.com/assets/424411/20667579/e48cc196-b561-11e6-92cf-485f65fb2233.gif)

Typing a word then hitting return will delete the last word:

[GIF](https://cloud.githubusercontent.com/assets/424411/20667608/09cee420-b562-11e6-943b-4db7797db6b5.gif)

(Although I'm not sure if that's exactly the steps to replicate. There's definitely some weirdness around hitting return)

I think we're going to ship 5.21 soon, as it does seem to be a bit more stable. Hopefully that will get us a bit more data on devices affected.

**Comment by louisatome** [comment] 2016-12-15 14:25
I experience the same problem of the new lines removed when write some text. It seems to be linked to the commit 6019b13 . If I revert this commit, the problem doesn't occur anymore.

**Comment by marijnh** [comment] 2017-03-09 16:00
The newlines vanishing issue should be fixed by cfcad600a6b27

I can't reproduce words disappearing when pressing enter

Backspace on line boundaries indeed seems to be broken when there is a gutter (opened #4637 for that)

Please open separate, single issues for remaining problems. Piling things up in a single issue report like this makes it hard to keep track of problems.

**Closed by marijnh** 2017-03-09 16:00 UTC
Labels: mobile
